param(
    [switch]$SkipInstall
)

$ErrorActionPreference = "Stop"

# PowerShell 7.3+ turns *any* stderr output from a native command into a
# terminating error while $ErrorActionPreference = "Stop". npm/vite print
# deprecation notices on stderr, so native exit codes are checked explicitly.
if (Test-Path variable:PSNativeCommandUseErrorActionPreference) {
    $PSNativeCommandUseErrorActionPreference = $false
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir "..")
Set-Location $repoRoot

$plugin = Get-Content -Raw -Encoding UTF8 "plugin.json" | ConvertFrom-Json
$expectedFrontendEntry = "ui/dist/index.js"
if ($plugin.entry.frontend -ne $expectedFrontendEntry) {
    throw "plugin.json entry.frontend must be $expectedFrontendEntry, got $($plugin.entry.frontend)"
}

$packageName = "qwenpaw-remote-plugin-$($plugin.version)"
$distRoot = Join-Path $repoRoot "dist"
$staging = Join-Path $distRoot $packageName
$zipPath = Join-Path $distRoot "$packageName.zip"

if (-not $SkipInstall) {
    # Routed through cmd.exe: with $ErrorActionPreference = "Stop", Windows
    # PowerShell 5.1 turns native stderr (npm deprecation notices) into a
    # terminating error, which would abort packaging before the ZIP is written.
    cmd /c "npm --prefix ui ci 2>&1"
    if ($LASTEXITCODE -ne 0) {
        throw "npm ci failed with exit code $LASTEXITCODE"
    }
}
cmd /c "npm --prefix ui run build 2>&1"
if ($LASTEXITCODE -ne 0) {
    throw "npm run build failed with exit code $LASTEXITCODE"
}

if (-not (Test-Path -LiteralPath (Join-Path $repoRoot "ui/dist/index.js") -PathType Leaf)) {
    throw "ui/dist/index.js was not generated by the frontend build."
}

Remove-Item -LiteralPath $distRoot -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $staging | Out-Null

Copy-Item -LiteralPath plugin.json, plugin.py, requirements.txt, README.md, LICENSE -Destination $staging
Copy-Item -LiteralPath remote -Destination $staging -Recurse

New-Item -ItemType Directory -Force -Path (Join-Path $staging "ui\dist") | Out-Null
Copy-Item -Path "ui\dist\*" -Destination (Join-Path $staging "ui\dist")

if (-not (Test-Path -LiteralPath (Join-Path $staging "ui/dist/index.js") -PathType Leaf)) {
    throw "ui/dist/index.js was not copied into the package staging directory."
}

Get-ChildItem -Path $staging -Recurse -Directory -Filter "__pycache__" | Remove-Item -Recurse -Force
Get-ChildItem -Path $staging -Recurse -File -Include "*.pyc", "*.pyo" | Remove-Item -Force

Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

Remove-Item -LiteralPath $zipPath -Force -ErrorAction SilentlyContinue
$zip = [System.IO.Compression.ZipFile]::Open(
    $zipPath,
    [System.IO.Compression.ZipArchiveMode]::Create
)
try {
    $stagingRoot = (Resolve-Path $staging).Path.TrimEnd("\", "/")
    Get-ChildItem -Path $staging -Recurse -File | ForEach-Object {
        $absolutePath = $_.FullName
        $entryName = $absolutePath.Substring($stagingRoot.Length + 1).Replace("\", "/")
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
            $zip,
            $absolutePath,
            $entryName,
            [System.IO.Compression.CompressionLevel]::Optimal
        ) | Out-Null
    }
}
finally {
    $zip.Dispose()
}

Write-Host "Created $zipPath"
